version: '3'

services:
  db:
    image: postgres:13.15-bullseye
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    container_name: misc-app-database
    volumes:
      - ./postgres:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 3001:3001
    env_file:
      - .env
    container_name: misc-app-services
    depends_on:
      - db
